//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomBelous914.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientContract()
        {
            this.CompetenceCheck = new HashSet<CompetenceCheck>();
        }
    
        public int IdClientContract { get; set; }
        public int IdContract { get; set; }
        public int IdService { get; set; }
        public int IdWorker { get; set; }
        public System.DateTime StartDateService { get; set; }
        public Nullable<System.DateTime> EndDateService { get; set; }
        public Nullable<int> IDActivityService { get; set; }
        public string Comment { get; set; }
    
        public virtual ActivityService ActivityService { get; set; }
        public virtual Contractt Contractt { get; set; }
        public virtual Service Service { get; set; }
        public virtual Worker Worker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetenceCheck> CompetenceCheck { get; set; }
    }
}
