//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomBelous914.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetenceCheck
    {
        public int IdCompetenceCheck { get; set; }
        public Nullable<int> IdClientContract { get; set; }
        public Nullable<int> IdCompetence { get; set; }
    
        public virtual ClientContract ClientContract { get; set; }
        public virtual Competence Competence { get; set; }
    }
}
