//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomBelous914.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int IdEducation { get; set; }
        public int IdWorker { get; set; }
        public string NameEducation { get; set; }
        public System.DateTime StartStudy { get; set; }
        public System.DateTime EndStudy { get; set; }
        public string Diploma { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
