//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomBelous914.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int IdSalary { get; set; }
        public int IdWorker { get; set; }
        public decimal AmountSalary { get; set; }
        public Nullable<System.DateTime> DateSalary { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
