//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomBelous914.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Client
    {
        public string Client { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string NameContract { get; set; }
        public Nullable<decimal> FullCost { get; set; }
        public string NameService { get; set; }
    }
}
