//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomBelous914.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Worker
    {
        public string Worker { get; set; }
        public string Competence { get; set; }
        public string NamePost { get; set; }
        public string NameEducation { get; set; }
        public string Diploma { get; set; }
    }
}
