//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomBelous914.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ServiceWorker
    {
        public int IdService { get; set; }
        public string NameService { get; set; }
        public int IdActivityService { get; set; }
        public string FullName { get; set; }
        public int IdPost { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime StartDateService { get; set; }
        public string NameActivity { get; set; }
        public string NameContract { get; set; }
        public Nullable<System.DateTime> EndDateService { get; set; }
        public int IdWorker { get; set; }
        public int IdClientContract { get; set; }
    }
}
